### ISSUE TITLE
Potential problem deleting wrong database

### ISSUE THREAD

**Issue by biolauri** [jnko/SimpleDatabaseBackup#6]
First of all: Thank you for your effort on this PlugIn! 👍 

I just poked a bit through the code and thought about the way [populating the bakFiles array](https://github.com/jnko/SimpleDatabaseBackup/blob/master/SimpleDatabaseBackup/SimpleDatabaseBackup.cs#L167): With the `_*.kdbx`-filter, it could be possible, that a non-backup database file gets added (and backup files from other databases). For example, if (an organisation) has the main database file *example.kdbx* and some other departments-only, like *example_support.kdbx*.  
Depending on the constellation and number of backups of both files, *example_support.kdbx* could be deleted on the next save/write-out of KeePass to *example.kdbx*.

If I'm not too tired to think clearly, one solution could be to append `.backup-[TIMESTAMP]` to all backup files.

I'm not affected by this problem (as I use a hyphen to separate my database file names), so it's nothing urgen. Just wanted to share my thoughts about this. :-)

**Comment by jnko** [comment]
Thanks for the hint!

Yes, you are right, this could become a very serious problem and I really should fix it.

**Comment by jnko** [comment]
I changed it a little bit to test for special extension '_sdbackup'

Thanks for reporting!

**Comment by biolauri** [comment]
Great and thanks! :)

I suppose, you forgot to push the source. I can't find anything [in the last 24 hours of commits](https://github.com/jnko/SimpleDatabaseBackup/compare/c587a1644b42085383e1dcd74ce659b1a53610fa...master). :D

**Comment by jnko** [comment]
@biolauri ...you're right...sorry.
